# ONE
http & graphql.get./lending_service_db/loanapplication/{id}:
  summary: Fetch LoanApplication
  description: Fetch LoanApplication from database
  fn: com.biz.lending_service_db.loanapplication.one
  params:
    - name: id
      in: path
      required: true
      schema:
        type: string
  responses:
    content:
      '200':
        application/json:
          schema:
            type: object

# CREATE
http & graphql.post./lending_service_db/loanapplication:
  summary: Create a new LoanApplication
  description: Create LoanApplication from database
  fn: com.biz.lending_service_db.loanapplication.create
  body:
    content:
      application/json:
        schema:
          $ref: '#/definitions/lending_service_db/LoanApplication'
  responses:
    content:
      '201':
        application/json:
          schema:
            type: object

# UPDATE
http & graphql.put./lending_service_db/loanapplication/{id}:
  summary: Update a LoanApplication
  description: Update LoanApplication from database
  fn: com.biz.lending_service_db.loanapplication.update
  body:
    content:
      application/json:
        schema:
          $ref: '#/definitions/lending_service_db/LoanApplication'
  params:
    - name: id
      in: path
      required: true
      schema:
        type: string
  responses:
    content:
      '204':
        application/json:
          schema:
            type: object

# DELETE
http & graphql.delete./lending_service_db/loanapplication/{id}:
  summary: Delete a LoanApplication
  description: Delete LoanApplication from database
  fn: com.biz.lending_service_db.loanapplication.delete
  params:
    - name: id
      in: path
      required: true
      schema:
        type: string
  responses:
    content:
      '202':
        application/json:
          schema:
            type: object

# SEARCH
http & graphql.post./lending_service_db/loanapplication/search:
  summary: Fetch multiple LoanApplication
  description: Fetch multiple LoanApplication from database
  fn: com.biz.lending_service_db.loanapplication.search
  body:
    content:
      application/json:
        schema:
          type: object
          example: {"include": {"user": {"select": {"pan_number": true}}}, "where": {"userId": 19}}

  responses:
    content:
      '200':
        application/json:
          schema:
            type: array

