# ONE
http.get./lending_service_db/loanapplication/{id}:
  summary: Fetch LoanApplication
  description: Fetch LoanApplication from database
  # To try with yaml work flow replace in fn name `ts` to `y_aml_fn` for eg lending_service_db.loanapplication.y_aml_fn.one 
  fn: lending_service_db_crud.loanapplication.ts.one 
  params:
    - name: id
      in: path
      required: true
      schema:
        type: string
  responses:
    content:
      application/json:
        schema:
          type: object

# CREATE
http.post./lending_service_db/loanapplication:
  summary: Create a new LoanApplication
  description: Create LoanApplication from database
  fn: lending_service_db_crud.loanapplication.ts.create
  authn: false
  authz: false
  body:
    content:
      application/json:
        schema:
          $ref: '#/definitions/lending_service_db/LoanApplication'
  responses:
    content:
      application/json:
        schema:
          type: object

# UPDATE
http.put./lending_service_db/loanapplication/{id}:
  summary: Update a LoanApplication
  description: Update LoanApplication from database
  fn: lending_service_db_crud.loanapplication.ts.update
  body:
    content:
      application/json:
        schema:
          $ref: '#/definitions/lending_service_db/LoanApplication'
  params:
    - name: id
      in: path
      required: true
      schema:
        type: string
  responses:
    content:
      application/json:
        schema:
          type: object

# DELETE
http.delete./lending_service_db/loanapplication/{id}:
  summary: Delete a LoanApplication
  description: Delete LoanApplication from database
  fn: lending_service_db_crud.loanapplication.ts.delete
  params:
    - name: id
      in: path
      required: true
      schema:
        type: string
  responses:
    content:
      application/json:
        schema:
          type: object

# SEARCH
http.post./lending_service_db/loanapplication/search:
  summary: Fetch multiple LoanApplication
  description: Fetch multiple LoanApplication from database
  fn: lending_service_db_crud.loanapplication.ts.search
  body:
    content:
      application/json:
        schema:
          type: object
  responses:
    content:
      application/json:
        schema:
          type: array

