
lang: js #js You can set 'coffee' or 'js' as your inline scripting language
caching: in_mem_cache
log: # log setting of the project
  redact: ['pan_number'] # []'a.b.c', 'a.b.*', 'req.headers']  #pino redact rules. Default null.
  attributes: #which OTEL attributes do you want to log in every log statement. Default null
    gender: mappings.GENDER.male
    headers: "headers.authorization"
  level: debug #by default info
  timestamp: stdTimeFunctions.isoTime
  sync: true #or false. By default sync is false
  bindings: #do you want to see pid and hostname in your log statements?
    pid: false
    hostname: false

# Any other settings for access in the project 
datasourceDB:
  name: lending_service_db

